apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-access-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-access-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-access-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pod-access-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-access-role
  apiGroup: rbac.authorization.k8s.io